- id: post-checkout
  name: git-lfs post-checkout hook
  language: python
  entry: git-lfs-hooks post-checkout
  # Since post-checkout doesn't operate on files, any hooks must set always_run
  always_run: true
  pass_filenames: false
  stages: [post-checkout]

- id: post-commit
  name: git-lfs post-commit hook
  language: python
  entry: git-lfs-hooks post-commit
  # Since post-commit does not operate on files, any hooks must set always_run
  always_run: true
  pass_filenames: false
  stages: [post-commit]

- id: post-merge
  name: git-lfs post-merge hook
  language: python
  entry: git-lfs-hooks post-merge
  always_run: true
  pass_filenames: false
  stages: [post-merge]

- id: pre-push
  name: git-lfs pre-push hook
  language: python
  entry: git-lfs-hooks pre-push
  always_run: true
  pass_filenames: false
  stages: [push]