name: Check Git LFS hooks and make a PR if necessary

on:
  push:
    branches:
      - 'test-github-actions'

jobs:
  git-lfs-hooks:
    runs-on: ubuntu-latest
    
    steps:

      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Install git-lfs
        run: |
          curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
      
      - name: Check if git-lfs is installed
        if: always()
        run: |
          mkdir tmp
          cd tmp
          git init
          git lfs update -m
          git lfs --version
          git lfs install
          ls -a
      
      - name: print pwd before checking out
        if: always()
        run: |
          pwd
          ls

      # - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: print pwd before after out
        run: |
          pwd
          ls
      
      - name: Copy files to hooks dir
        run: |
          cp -a tmp/.git/hooks/. hooks/
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "update: Update Git LFS hooks"
          branch: "test/git-lfs-hooks-update"
          delete-branch: true
          title: "update: Update Git LFS hooks"
          body: >
            The following PR updates the GIT LFS hooks.
          labels: automated pr, pre-commit