name: Check Git LFS hooks and make a PR if necessary

on:
  push:
    branches:
      - 'test-github-actions'

jobs:
  git-lfs-hooks:
    runs-on: ubuntu-latest
    
    steps:

      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Check Git LFS for updates
        run: |
          ./update-from-git-lfs.sh
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "update: Update Git LFS hooks"
          branch: "test/git-lfs-hooks-update"
          delete-branch: true
          title: "update: Update Git LFS hooks"
          body: >
            The following PR updates the GIT LFS hooks.
          labels: automated pr, pre-commit